#!/bin/bash
# shellcheck disable=SC2154
install_netfilter_extras() {	# This "install_netfilter_extras" snippet of code was AI Generated by Cluade

    echo "Installing kernel-modules-extra..."
    sudo dnf install -y kernel-modules-extra

    echo "Loading xt_mark..."
    sudo modprobe xt_mark

    echo "Persisting across reboots..."
	grep -qxF "xt_mark" /etc/modules-load.d/xt_mark.conf 2>/dev/null || \
    echo "xt_mark" | sudo tee -a /etc/modules-load.d/xt_mark.conf
}


docker_override(){
	# Makes the directory if it isn't already
	sudo mkdir -p /etc/systemd/system/docker.service.d
	# Copies over the override into the override.conf.
	sudo cp ./distros/rocky/docker-override.conf /etc/systemd/system/docker.service.d/override.conf
	# Reloads the daemon to make sure it applied.  
	sudo systemctl daemon-reload
}

sshd_override(){
	# Makes the directory if it isn't already
	sudo mkdir -p /etc/systemd/system/sshd.service.d
	# Copies over the override into the override.conf.
	sudo cp ./distros/rocky/sshd-override.conf /etc/systemd/system/sshd.service.d/override.conf
	# Reloads the daemon to make sure it applied.  
	sudo systemctl daemon-reload
}

rocky_specific(){
	docker_override
	sshd_override
}