#!/bin/bash
rocky_docker(){
#remove old docker, just in case it's there. So we start fresh. 
sudo dnf remove -y docker \
				  docker-client \
				  docker-client-latest \
				  docker-common \
				  docker-latest \
				  docker-latest-logrotate \
				  docker-logrotate \
				  docker-engine \
				  podman \
				  runc

sudo dnf install dnf-plugins-core -y

sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y 
#enable docker to start on boot, and also to start it now. 
sudo systemctl enable --now docker


#create the folder where I store my apps and services. 
sudo mkdir -p /opt/docker/
configure_docker_selinux
}

configure_docker_selinux() { # This "configure_docker_selinux" snippet of code was AI Generated by Cluade.
    local docker_data_dir="/opt/docker"
    
    if ! command -v semanage &>/dev/null; then
        echo "semanage not found, installing policycoreutils-python-utils..."
        sudo dnf install -y policycoreutils-python-utils
    fi

    sudo semanage fcontext -a -t container_file_t "${docker_data_dir}(/.*)?" 2>/dev/null || \
        sudo semanage fcontext -m -t container_file_t "${docker_data_dir}(/.*)?"
    sudo restorecon -Rv "${docker_data_dir}"
}